### ISSUE TITLE
Add Bash completion

### ISSUE THREAD

**Issue by vsund** [palortoff/pass-extension-tail#4]
Hey, first of all thank you for this great extension!

I'd like to suggest to add bash completion. Shouldn't be that much work (there are only two commands :)).

What do you think?

**Comment by palortoff** [comment]
bash completion would be great, I agree.
But as far as I understand completion, completion must be configured for the base command `pass`. On my systems I edited the pass completion file `pass.bash-completion` and added the `tail` and `tailedit` commands to the list of commands in line 84 and to the ls and edit command in line 97.
I know, this is only a workaround. Maybe one day pass supports completion for extensions.

**Comment by willpower232** [comment]
Please can you add those steps for completion to `README.md` as they're a massive lifesaver?

**Comment by palortoff** [comment]
done!

**Comment by palortoff** [comment]
With version  1.7.3  password-store added bash completion support for bash.

pass-extension-tail now has built-in pass completion when installed.

**Comment by gavin09** [comment]
I get following warning messages when I try to package v1.2.0 into Debian.

```
pass-extension-tail: package-installs-into-obsolete-dir etc/bash_completion.d/ :
^etc/bash_completion.d/ -> usr/share/bash-completion/completions
Ensure new filename matches sticter requirements
(see https://bugs.debian.org/776954 and https://bugs.debian.org/814599)
```

However, simply install completion/pass-tail.bash.completion to newer path cannot work. I think the root cause is the newer path does not source dirs[1]. It seems like newer path needs to do in other way, but I have no good idea right now.

Any ideas?

[1] https://salsa.debian.org/debian/bash-completion/blob/9add9c788d6af890fb0fa4b236dd184f6ead768a/bash_completion#L2035

**Comment by willpower232** [comment]
I noticed this too but it still works for me.

I had a look at how `pass` itself handles this and it checks which shell you're in when you install and then puts the completion file in the appropriate place which might be the way to go here if the current directory is obsolete.

See https://git.zx2c4.com/password-store/tree/Makefile

**Comment by gavin09** [comment]
I know `pass` can check which shell user is in.

The problem is: completion/pass-tail.bash.completion currently installs to /etc/bash_completion.d/ which is now obsolete.
I’m the maintainer of this package on Debian[1]. 
I think it is better to upload a version into Debian which fixes this warning message.

I’m trying to figure out how to make bash completion work if pass-tail.bash.completion installs to /usr/share/bash-completion/completions. Any suggestion?

[1] https://tracker.debian.org/pkg/pass-extension-tail

**Comment by palortoff** [comment]
First of all, sorry for being quiet on this issue for so long.
Thanks to you both for looking into it.

@willpower232: changing the extension to install the completion into `/usr/share/bash-completion/completions/` will not work. The bash completion file for pass-extension-tail is not a completion in itself, but a 'mod' for the extension for pass. It does not call complete but modifies the environment (env variables and functions) so that the pass completion recognizes the extension command at run time. It has to be sourced, there is no other way as far as I see it.

@gavin09:  From reading  `bash-completion`, there are currently two folders being sourced by it. `/etc/bash_completion.d`  and `~/.bash_completion`. Will `~/.bash_completion` go away as well? Or will `bash_completion` itself no longer be sourced by default in the future?

As far as I see, the default `.bashrc` only source `~/.bash_aliases~ and  `bash_completion`. Therefore the only place out of the user's scope currently is `/etc/bash_completion.d`

With this going away it might be necessary to patch the completion script of pass itself to read the extension completion 'mods' instead of just using them...

**Comment by palortoff** [comment]
@gavin09 why is `etc/bash_completion.d/` being deprecated by debian? I cannot see any indication for that in [bash-completion](https://github.com/scop/bash-completion). 
The [linked issue](https://salsa.debian.org/debian/bash-completion/blob/9add9c788d6af890fb0fa4b236dd184f6ead768a/bash_completion#L2035) hints to a bug in bash that leaks file descriptors when sourcing, but that has been fixed since bash 4.3

**Comment by palortoff** [comment]
I sent a patch to password-store for a bash completion approach that does not rely on sourcing and does not need /etc/bash_completion.d
When this patch is applied to the password store I can change completion for this extension.

**Comment by gavin09** [comment]
Sorry for the late reply

To my understanding, /etc/bash_completion.d is sourced at bash startup. After bash-completion v2.0, it provides completion script for dynamically loading. I think this is the main reason etc/bash_completion.d is deprecated.

Reference:
https://github.com/scop/bash-completion/blob/master/doc/bash_completion.txt#L22
https://public-inbox.org/git/20180429140920.GA570@furore/T/
